spring:
  application:
    name: sample-consumer
  jms:
    listener:
      session:
        acknowledge-mode: '101'
        transacted: false
  qpidjms:
    broker-url: amqp://localhost:5672
---
spring:
  config:
    activate:
      on-profile: azure-servicebus
  qpidjms:
    username: RootManageSharedAccessKey
    password: SAS_KEY_VALUE
