spring:
  application:
    name: sample-producer
  jms:
    template:
      session:
        acknowledge-mode: '101'
---
spring:
  config:
    activate:
      on-profile: azure-servicebus
  qpidjms:
    username: RootManageSharedAccessKey
    password: SAS_KEY_VALUE
