spring:
  application:
    name: sample-producer
  qpidjms:
    broker-url: amqp://localhost:5672
---
spring:
  config:
    activate:
      on-profile: azure-servicebus
  qpidjms:
    username: RootManageSharedAccessKey
    password: SAS_KEY_VALUE
---
spring:
  config:
    activate:
      on-profile: rabbitmq
  qpidjms:
    username: guest
    password: guest
---
spring:
  config:
    activate:
      on-profile: artemis
  qpidjms:
    username: artemis
    password: artemis
